# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
build_env: &build_env
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.11.1

test_env: &test_env
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.11.1
      - image: circleci/mysql:5.7.22
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
          MYSQL_ROOT_HOST: '%'
      - image: circleci/redis:4.0.10

version: 2
jobs:
  build:
    <<: *build_env
    steps:
      - checkout
      - run:
          name: pwd
          command: pwd
      - run:
          name: ls
          command: ls -altr
      - run:
          name: touch
          command: touch from-build-job
      - persist_to_workspace:
          root: ~/repo # workspaceのrootパス（絶対パスかworking_directoryからの相対パス）
          paths:
            - . # 共有するパス（rootからの相対パス）

  test:
    <<: *test_env
    steps:
      - attach_workspace: # workspaceをアタッチする
          at: ~/repo
      - run:
          name: test-pwd
          command: pwd
      - run:
          name: test-ls
          command: ls -altr
      - run:
          name: Install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: 'v0.6.1'
      - run:
          name: Wait for mysql
          command: ./dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Wait for redis
          command: ./dockerize -wait tcp://localhost:6379 -timeout 1m

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires: # buildが成功したら実行する
            - build

